version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      npm-dev-minor-patch:
        dependency-type: development
        exclude-patterns:
          - vitest
          - vite
          - typescript
          - tsx
          - rollup
          - rolldown
          - esbuild
        update-types:
          - minor
          - patch
      npm-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: "/nova"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      npm-dev-minor-patch:
        dependency-type: development
        exclude-patterns:
          - vitest
          - vite
          - typescript
          - tsx
          - rollup
          - rolldown
          - esbuild
        update-types:
          - minor
          - patch
      npm-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      github-actions-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      github-actions-major:
        patterns:
          - "*"
        update-types:
          - major
