export type CloudSourceRunOptions = {
  action?: "completed" | "in_progress";
  associationPresentSequence?: boolean[];
  associationMergeCommitSHA?: null | string;
  bashExit?: number;
  conclusion?: "cancelled" | "failure" | "success";
  event?: "merge_group" | "pull_request";
  gitSHA?: null | string;
  gitSHASequence?: Array<null | string>;
  initialChecks?: unknown[];
  mergeCommitSHA?: null | string;
  mergeCommitSHASequence?: Array<null | string>;
  mergeCommitResponses?: Array<{
    parents?: string[];
    sha?: string;
    status?: number;
  }>;
  mergeCommitBaseSHASequence?: string[];
  monotonicNowSequence?: number[];
  checkListStatusAfterPatch?: number;
  checkReadStatus?: number;
  deleteStatus?: number;
  deleteStatusSequence?: number[];
  lateVisibleChecks?: unknown[];
  lateVisibleChecksDelay?: number;
  patchStatus?: number;
  patchThrowsAfterApply?: boolean;
  postReconcileListStatusSequence?: number[];
  postThrowsBeforeApply?: boolean;
  postThrowsAfterApply?: boolean;
  postVisibilityDelay?: number;
  pullCount?: number;
  currentWorkflowStatus?: "completed" | "in_progress";
  currentWorkflowAttempt?: number;
  currentWorkflowAttemptSequence?: number[];
  currentWorkflowStatusSequence?: Array<"completed" | "in_progress">;
  workflowAPIStatus?: number;
  workflowAPIStatusSequence?: number[];
};
